### PR TITLE
Add Story Sharing help

### PR DESCRIPTION
**Pull request by llewelld**
Adds a flow chart to illustrate the story sharing process, along with some explanatory text, to the help pages.

Contributes to #535.

### CODE REVIEW

**Comment by llewelld** [comment]
I've added the drawio source to the `static/images` folder, but I'm certain this is the wrong place, (we don't need it served on the final site). Any suggestions for where it should go? Maybe we don't need it stored in the repo at all?

**Comment by llewelld** [comment]
A preview:

image

**Review by gedankenstuecke — APPROVED** [review]
That's a great addition! 

Regarding the question of where to put the source file: It's an excellent question. Generally I'd say somewhere in the `00-project-documentation` folder could be a good fit. It's a bit hidden but `00-project-documentation/platform-design/platform-design/platform-content` seems like it could fit?

**Review by gedankenstuecke — APPROVED** [review]
Thanks, then I'd say this is good to go!

**Pull request merged**
