### PR TITLE
Frontend implementation of the platform 

### PR DESCRIPTION
**Pull request by soledadli**

### CODE REVIEW

**Comment by BrainonSilicon** [comment]
Hi @soledadli! Awesome work on the platform's design!!! It's so cool to see it implemented. 

I'll go through this PR in the next few days and add any review comments that would be helpful.

**Comment by GeorgiaHCA** [comment]
This is truly fantastic work @soledadli ! I've been looking at the deployed version and the design is awesome. There are a few things I've noticed around the text content and flow which need changing but I think this makes sense to add as separate issues and fix forwards so we can get this merged to the main repo!

**Comment by GeorgiaHCA** [comment]
Are you able to take a look @BrainonSilicon? Do you reckon we can go ahead and merge this now?

**Comment by callummole** [comment]
@helendduncan and I reviewed most of this today. I think the design is really nice. There are obviously bits that we would want to change (e.g. hardcoded experiences, some links here and there not working...), but I think we should merge this to main now, and branch off from there, since the whole site is still in dev. This PR makes a big positive change to the look and feel of the site, well done @soledadli!

**Comment by callummole** [comment]
@GeorgiaHCA @BrainonSilicon do we have a practice for merging? I'd be happy to just go ahead and merge but want to check how you work first.

**Pull request merged**
