### PR TITLE
Navigation: Standardize Moderation page nav bar

### PR DESCRIPTION
**Pull request by mridubhatnagar**
Pull request for issue https://github.com/alan-turing-institute/AutSPACEs/issues/137

Screenshot from 2021-07-24 20-18-31

### CODE REVIEW

**Comment by mridubhatnagar** [comment]
@jhlink this PR needs to be reviewed as well.

**Comment by anoura12** [comment]
@mridubhatnagar I think I can add it. Shall I do that for you?

**Comment by mridubhatnagar** [comment]
@anoura12 I think doing it this way would make it difficult to test the whole thing. Not sure though.

**Comment by anoura12** [comment]
> @anoura12 I think doing it this way would make it difficult to test the whole thing. Not sure though.

I meant adding James as a reviewer
Already did it for you now.

**Comment by mridubhatnagar** [comment]
> > @anoura12 I think doing it this way would make it difficult to test the whole thing. Not sure though.
> 
> I meant adding James as a reviewer
> Already did it for you now.

Oh... I thought you were talking with reference to the issue we were discussing yesterday.
Thanks for adding James as the reviewer :)

**Review by jhlink — CHANGES_REQUESTED** [review]
Hey @mridubhatnagar !! Great work so far!!

Here are the changes that are still missing from #137 . 

- Logout button should still log out user
- Logout button should direct user to `home.html` or `landing.html` not `overview.html`. 
- There should not be a Login button in the nav bar.

**Comment by mridubhatnagar** [comment]
@jhlink fixed the issues. 
Have made changes in the views.py file in another PR once it gets merged. The logout button here will redirect to landing.html.

**Comment by jhlink** [comment]
Brilliant work, @mridubhatnagar !! Changes are good! 🥳 

Merging.

**Pull request merged**
