### PR TITLE
Moderation navbar

### PR DESCRIPTION
**Pull request by anoura12**

### CODE REVIEW

**Comment by anoura12** [comment]
@jhlink There was a small merge conflict at the end as I had to incorporate the new view experiences url link in the code. Hence, the 'Resolve Conflicts' commit

**Comment by jhlink** [comment]
Hey @anoura12 , I can't merge this PR. 
CleanShot 2021-08-04 at 09 46 33@2x

It creates a ReverseMatch error when I try out your branch. 

What I recommend is checking out the `navigate_view_experiences` branch, making this change there, and submitting the PR with all the changes you've made.

**Review by jhlink — CHANGES_REQUESTED** [review]
Still looking for the navigate_view_experiences changes. 
Current change breaks site.

**Comment by anoura12** [comment]
@jhlink So in the navigate_view_experiences branch, do i only make the change in the url name and the revert the navbar changes in this PR?

**Comment by jhlink** [comment]
@anoura12 , so, within the navigate_view_experiences branch, 
- [ ] Revert the change to the moderate_public_experiences page that was the result of the merge conflit. 
- [ ] Then* apply the changes you've made in this PR to the `navigate_view_experiences` branch.
- [ ] Make a PR for navigate_view_experiences

**Comment by anoura12** [comment]
Yes, I think I've included these changes in the PR I just made. 
Could you check that one?

**Pull request closed without merging**
