### PR TITLE
Added landing page

### PR DESCRIPTION
**Pull request by anoura12**
Currently I've added them under the templates section and I've kept the original files as well. Shall we keep the original files till we complete Milestone 3 so that we can use those for reference while trying to integrate these new files into Django?

### CODE REVIEW

**Comment by jhlink** [comment]
Can you separate this PR into two different PRs? It looks like you're combing #15  and #16 , which isn't good practice. 

PRs should accomplish one feature or one task. Bundling them makes it difficult to unravel or debug for future contributors.

**Comment by jhlink** [comment]
@anoura12 , no. It's not necessary to keep the original files since they're already managed by github. 

I think I'm missing something... I'm not able to see your changes when building the website. 

CleanShot 2021-06-22 at 05 44 16@2x

CleanShot 2021-06-22 at 05 44 56@2x

**Comment by jhlink** [comment]
Hey @anoura12 , looks like you're still missing three of the items on this checklist. 

https://github.com/alan-turing-institute/AutSPACEs/issues/15

For now, I'll change this PR into a draft until you make those changes.

**Comment by anoura12** [comment]
Hi @jhlink, I've made the changes according to the list in the issue. Could you take a look at them?

**Comment by jhlink** [comment]
> Hi @jhlink, I've made the changes according to the list in the issue. Could you take a look at them? 

Sure! I'll review them within the next day or two! !

**Comment by jhlink** [comment]
Wonderful!! Great work, @anoura12 !!
This issue closes #15

**Pull request merged**
