### PR TITLE
[Ready for Review] Explicit confirmation of profile changes - flexible confirmation pages

### LINKED ISSUE #587: User Testing: Profile updates
### Summary

In user testing the following comments/issues arose

There is no confirmation after profile save
Where would be sensible to redirect after profile changes - explicit confirmation (thank you for completing your profile....) Then to "My Stories" page which will have an "Add story" button
Work with a more flexible "Success" page

### Deadline 
Mid October 2023

### What needs to be done?
- [x] Explicit confirmation after profile save
- [x] Redirect after profile changes
- [x] Re-use/factor the "Success" page

### PR DESCRIPTION
**Pull request by helendduncan**
closes #587 and #588

### CODE REVIEW

**Comment by helendduncan** [comment]
I've started working on the flexible confirmation page - specifically after adding/editing a story. This is where I am at the moment, and I have a couple of questions on wording and comprehension.
The two "what happens now" lines are specific to the submitted/edited story and should make it more clear what is viewable and what is private. However you get to a situation where someone has a private story, but if they agree to share it with researchers the messages become a bit contradictory. Could @gedankenstuecke and @GeorgiaHCA have a look and let me know what you think?
Screenshots below

Screenshot 2023-10-13 at 13 56 28
Screenshot 2023-10-13 at 13 57 51
Screenshot 2023-10-13 at 14 16 54

**Comment by gedankenstuecke** [comment]
That's some great progress, well done @helendduncan! 

I would suggest the following phrasing/wording: 

1. Top-headline: __Success!__ , regardless of options

for the 2nd level headline: 
1. Only if neither sharing for research nor for public: _Your experience was saved_
2. otherwise: "Thank you for sharing your experience" 

Then for the text below the two respective alternatives: 

Public/not public sharing: 
1. public: "As you chose to publicly share your experience, a moderator will check that it follows our code of conduct, and if it does, you will receive a confirmation and your experience will then be published on this website.
2. private: "Your experience will not be publicly accessible on AutSPACEs" 

Research/not research: 
1. research: As you chose to share your experience with researchers, your experience will be part of the AutSPACEs research data set to which researchers that are aligned with our values and follow our code of conduct can apply for access to. 
2. not research: Your experience will not be part of the AutSPACEs research data set.

I think with this any combinations still make sense, what do you think @helendduncan @GeorgiaHCA? 🙂

**Comment by helendduncan** [comment]
Thanks @gedankenstuecke - with respect to the second headline does it make sense to keep the distinction between sharing and editing?

**Comment by gedankenstuecke** [comment]
Good question, I guess we could add “new” or “edited” before the experience to be more clear?

**Review by gedankenstuecke — APPROVED** [review]
Sorry for the long delay on properly reviewing this @helendduncan! I've just given it a spin across all options and it looks & works great! 

Happy to have this merged in! 🚀

**Pull request merged**
