### PR TITLE
Navigate: View Experiences (Revert Changes)

### PR DESCRIPTION
**Pull request by anoura12**

### CODE REVIEW

**Comment by jhlink** [comment]
Okay. This was your original PR. 

https://github.com/alan-turing-institute/AutSPACEs/pull/147/files

I need to see all the changes you've made in these files *except* for certain changes made from the merge conflict. 
Specifically
- [ ] The Moderation page 
CleanShot 2021-08-04 at 11 03 59@2x

The changes you've added in your other PR are okay to add to this branch, but the bigger issue is that none of your work from #147 has carried over.

**Comment by jhlink** [comment]
When I checkout out this branch and run the docker instance, none of the changes you've made to the `View Experiences` page are showing up. :( 

CleanShot 2021-08-04 at 11 06 45@2x

**Comment by anoura12** [comment]
Oh, so as I understand, when I push changes to this particular PR, the previous changes I made to the original PR aren't being reflected here. Hence, the whole NoReverseMatch conflict comes up right?

**Comment by jhlink** [comment]
The Pull Request is a reflection of the changes you made on the branch. 
This PR and the original PR are snapshots of that branch. 

For some reason, all the changes `View Experience` page changes that are required [here](https://github.com/alan-turing-institute/AutSPACEs/issues/135) have been removed from your `navigate_view_experiences` branch. 

The reason why the `NoReverseMatch` conflict occurs is because the changes you've made in this PR are incompatible with the current `main` branch. You need to make them compatible by incorporating the *original* changes you've made. 

Does that make sense?

**Comment by anoura12** [comment]
Ohhhh okay..so I need to push the original changes here as well then?

**Comment by anoura12** [comment]
> @jhlink I think if she takes the pull of the main branch on her current branch the original changes would come (if the original PR was merged)

Yeah i think the problem is that the original PR got reverted. So, the changes didn't get merged

**Comment by mridubhatnagar** [comment]
oh.... does that mean a completely new PR having both your old changes(original changes) as well as the new changes.

**Comment by anoura12** [comment]
> oh.... does that mean a completely new PR having both your old changes(original changes) as well as the new changes.

Yes, I believe so

**Comment by jhlink** [comment]
@anoura12 , yes. You need all the original changes. Luckily, I've made a copy of the old branch here. 
If you merge `old_navigate_view_experiences` into `navigate_view_experiences`, you should have all your original changes + new changes. 

The reason you can't push any changes to the old PR is because it's already closed/merged.

**Comment by anoura12** [comment]
@jhlink That sounds good. I've merged the old_naviagte_view_experiences to this branch. Hope it works now! :crossed_fingers:

**Comment by anoura12** [comment]
Okay @jhlink I did make the new commits but I think in the cherry picking process, I accepted my changes instead of the incoming changes..so i guess I made my own commits in the process. I think it should work now

**Review by jhlink — APPROVED** [review]
Okay. Ran your PR, and the changes are good. Merging.

**Comment by jhlink** [comment]
This PR closes #135

**Pull request merged**
