### PR TITLE
[WIP]Add files via upload

### PR DESCRIPTION
**Pull request by sowmya9507**
Static files of user creating an account and viewing experiences

### CODE REVIEW

**Comment by jhlink** [comment]
Is this ready for review? If not, I recommend converting this PR to a draft. Helps clarify whether something is ready for review or currently in progress. 
CleanShot 2021-06-09 at 23 32 21@2x

**Comment by sowmya9507** [comment]
@jhlink sorry for that. Sure I will do that.

**Comment by lottycoupat** [comment]
@sowmya9507 to change this to [WIP]

**Comment by jhlink** [comment]
@sowmya9507 , is this PR ready for review?

**Comment by sowmya9507** [comment]
@jhlink I have added the PR for each issue separately. So this PR is not required anymore. Shall I go ahead and close or delete it?

**Comment by jhlink** [comment]
> @jhlink I have added the PR for each issue separately. So this PR is not required anymore. Shall I go ahead and close or delete it? 

I think closing it is fine. :)

**Comment by sowmya9507** [comment]
Okie! Awesome :) Shall do! :)

**Pull request closed without merging**
