### PR TITLE
Navigation: Standardize My Stories page nav bar

### PR DESCRIPTION
**Pull request by mridubhatnagar**
pull request for issue https://github.com/alan-turing-institute/AutSPACEs/issues/136

### CODE REVIEW

**Comment by mridubhatnagar** [comment]
@jhlink, I have finished all the subtasks mentioned on the Navigation: Standardize My Stories page navbar #136 task. I am a bit confused about how to test the logout functionality?

I tried logging out by clicking on logout on the navigation bar it redirects to the landing page but on the navbar of the landing page, I see the logout option again.

**Comment by jhlink** [comment]
> @jhlink, I have finished all the subtasks mentioned on the Navigation: Standardize My Stories page navbar #136 task. I am a bit confused about how to test the logout functionality?
> 
> I tried logging out by clicking on logout on the navigation bar it redirects to the landing page but on the navbar of the landing page, I see the logout option again. 

Can you share a screengrab of what you're seeing, @mridubhatnagar ?

**Comment by mridubhatnagar** [comment]
My Stories Page

Screenshot from 2021-07-17 19-24-57

After clicking logout on my stories page user is redirected to the below page (landing.html)

Screenshot from 2021-07-23 15-21-05

**Comment by mridubhatnagar** [comment]
My Stories Page

my_stories_page

After clicking logout on my stories page user gets redirected to the below-mentioned page.
after_clicking_logout

**Review by jhlink — CHANGES_REQUESTED** [review]
@mridubhatnagar , hey Mridu. Everything is great except the logout functionality doesn't work. 

You can test this by trying to navigate to `http://localhost:8000/main/my_stories` after you logged out. 
You can see how the logout functionality currently works by clicking logout on `http:/localhost:8000/main/overview`. You'll notice that clicking logout here will prevent you from loading `/main/my_stories` or even `/main/overview`

**Comment by mridubhatnagar** [comment]
@jhlink, thanks for explaining it.

Pushed the changes.

**Comment by jhlink** [comment]
Wonderful!! Nicely done, @mridubhatnagar !!
Merging!!

**Pull request merged**
