### PR TITLE
Navigation: Standardize Confirmation page nav bar

### PR DESCRIPTION
**Pull request by mridubhatnagar**
PR for issue https://github.com/alan-turing-institute/AutSPACEs/issues/139

Screenshot from 2021-07-23 23-16-04

### CODE REVIEW

**Comment by mridubhatnagar** [comment]
@jhlink, I have fixed the issues mentioned in https://github.com/alan-turing-institute/AutSPACEs/issues/139.

The fix for the below mentioned issues is dependent on PR https://github.com/alan-turing-institute/AutSPACEs/pull/141. PR https://github.com/alan-turing-institute/AutSPACEs/pull/141 has one change in the views file. Once PR https://github.com/alan-turing-institute/AutSPACEs/pull/141 is merged the following issues on their own will be working as expected.

- [ ]  Clicking Home directs user to the Home page
     This is landing.html not overview.html
- [ ]  Clicking Logout directs user to Home page.
      This is home.html or landing.html not overview.html
- [ ] Clicking Find out more about AutSPACEs directs user to Home page.
       This is home.html or landing.html not overview.html

**Comment by jhlink** [comment]
Great! I'll review this in the next few days! Thanks!!

**Review by jhlink — CHANGES_REQUESTED** [review]
Hey @mridubhatnagar , great work!

So far, here are the changes that are missing with respect to #139 . 
- `Home`, `Logout`, and `Find out more about AutSPACEs` need to direct the user to `landing.html`. 
- The logout functionality isn't working for the user.

**Comment by mridubhatnagar** [comment]
@jhlink yes. Actually when you merge PR https://github.com/alan-turing-institute/AutSPACEs/pull/141 the landing page issue will get fixed. As I have made changes in the views.py file.

Logout functionality yes I am fixing it now.

**Comment by mridubhatnagar** [comment]
@jhlink when other PR's get merged this PR would also work as expected. 
As the views file has got changed in other PR's.

**Comment by jhlink** [comment]
@mridubhatnagar , PR #141 has been merged, but I don't see the changes you're talking about on the docker instance. Could you apply the changes and tag me for a re-review?

**Comment by mridubhatnagar** [comment]
@jhlink can you check now?

Though on my local I am able to see the changes.
I have now merged the main branch with the branch of this PR.

**Comment by jhlink** [comment]
Great!! @mridubhatnagar I see the changes now! 
Merging.

**Pull request merged**
