### PR TITLE
Rearrange the navbar

### PR DESCRIPTION
**Pull request by llewelld**
Changes the structure of the navigation menu bar at the top of every page, following feedback from user testing.

Contributes to #592.

### CODE REVIEW

**Comment by llewelld** [comment]
An image capture of the new structure:

image

**Comment by llewelld** [comment]
Issue #592 also has the Moderation drop down turned into tabs on the Moderation page, but I'd quite like to separate this off into its own PR. I've therefore moved this out of draft.

**Review by gedankenstuecke — APPROVED** [review]
This looks good to me. 

I think we had also considered to keep a "share stories" point around even when not logged in, which would take people to a landing page explaining how to contribute, but that might be a bigger change that's best left for another PR? :)

**Comment by llewelld** [comment]
Thanks for the approval @gedankenstuecke. There are now a couple of changes to make on top of this (changing "Share Stories" to "Add Story" and retaining it when logged out). I'll merge this so we can build on these changes in a separate PR.

**Pull request merged**
