### PR TITLE
Create MVP-requirements-list.md

### PR DESCRIPTION
**Pull request by GeorgiaHCA**
This is a very basic MVP requirements list for the most simple platform build which should link to Milestone 2 issues

### CODE REVIEW

**Comment by GeorgiaHCA** [comment]
Hey @lottycoupat, @jhlink, and @sowmya9507 - would you be able to take a look at this PR? Does it make sense? Should anything else be on here? It should match up to the MVP issues. Thanks! 🌟

**Comment by lottycoupat** [comment]
Does it need something along the lines of "abiding to GDS accessibility standards" ?

**Comment by GeorgiaHCA** [comment]
Yep, good point @lottycoupat - I've now grouped all the issues relating to that under Milestone 3

**Comment by GeorgiaHCA** [comment]
I've added a mini commit to address this @lottycoupat

**Review by lottycoupat — APPROVED** [review]
Looks good to me with added accessibility point 😄

**Comment by sowmya9507** [comment]
@GeorgiaHCA this looks good to me as well :)

**Pull request merged**
